package com.danbi.domain.onboarding.dto;

public enum OnboardingStep {
	NAME_INPUT,
	PHONE_OWNERSHIP,
	PHONE_VERIFICATION,
	CERTIFICATE_ISSUANCE,
	CERTIFICATE_TERMS,
	ID_CARD_SCAN,
	ID_CARD_CONFIRMATION,
	FACE_VERIFICATION
}
